<?php
namespace ITE;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-09-10 at 16:25:40.
 * @group ite
 * @group mysql
 * 
 */

class mysqlTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Error handler trait.
     */
    use errorHandler;
    
    /**
     * @var mysql
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     * @expectedExcpetion PHPUnit_Framework_Error
     */
    protected function setUp()
    {
        $this->initErrorHandler();
        $_ITE = ite::singleton();
        $this->object = new mysql($_ITE);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ITE\mysql::reconnect
     * @todo   Implement testReconnect().
     * @expectedExcpetion PHPUnit_Framework_Error
     */
    public function testReconnect()
    {
        $this->assertError("Enlace a BDD temporal: default DB parameters.",E_USER_WARNING);
        
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
        
        
    }

    /**
     * @covers ITE\mysql::bd_connect
     * @todo   Implement testBd_connect().
     */
    public function testBd_connect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::log
     * @todo   Implement testLog().
     */
    public function testLog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::consultar
     * @todo   Implement testConsultar().
     */
    public function testConsultar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::select
     * @todo   Implement testSelect().
     */
    public function testSelect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::free_query
     * @todo   Implement testFree_query().
     */
    public function testFree_query()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::insertar
     * @todo   Implement testInsertar().
     */
    public function testInsertar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::insert
     * @todo   Implement testInsert().
     */
    public function testInsert()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::editar
     * @todo   Implement testEditar().
     */
    public function testEditar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::borrar
     * @todo   Implement testBorrar().
     */
    public function testBorrar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::get_columns_info
     * @todo   Implement testGet_columns_info().
     */
    public function testGet_columns_info()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::field_label
     * @todo   Implement testField_label().
     */
    public function testField_label()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::varchar_field
     * @todo   Implement testVarchar_field().
     */
    public function testVarchar_field()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::int_field
     * @todo   Implement testInt_field().
     */
    public function testInt_field()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::double_field
     * @todo   Implement testDouble_field().
     */
    public function testDouble_field()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::date_field
     * @todo   Implement testDate_field().
     */
    public function testDate_field()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::datetime_field
     * @todo   Implement testDatetime_field().
     */
    public function testDatetime_field()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::time_field
     * @todo   Implement testTime_field().
     */
    public function testTime_field()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::id_field
     * @todo   Implement testId_field().
     */
    public function testId_field()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::enum_field
     * @todo   Implement testEnum_field().
     */
    public function testEnum_field()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::text_field
     * @todo   Implement testText_field().
     */
    public function testText_field()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::hidden_field
     * @todo   Implement testHidden_field().
     */
    public function testHidden_field()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::field_config
     * @todo   Implement testField_config().
     */
    public function testField_config()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::create_add_form_fields
     * @todo   Implement testCreate_add_form_fields().
     */
    public function testCreate_add_form_fields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::create_edit_form_fields
     * @todo   Implement testCreate_edit_form_fields().
     */
    public function testCreate_edit_form_fields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::create_add_form
     * @todo   Implement testCreate_add_form().
     */
    public function testCreate_add_form()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::create_edit_form
     * @todo   Implement testCreate_edit_form().
     */
    public function testCreate_edit_form()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ITE\mysql::create_table_rows
     * @todo   Implement testCreate_table_rows().
     */
    public function testCreate_table_rows()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
